---
apiVersion: v1
kind: Service
metadata:
  name: grpc-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hello
    tier: grpc
    track: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000