apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellohttp
  labels:
    app: hello
    tier: http
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      tier: http
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: http
        track: stable
    spec:
      containers:
        - name: hellohttp
          image: fransoaardi/hellohttp:v1
          ports:
            - containerPort: 8100