apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloserve
  labels:
    app: hello
    tier: serve
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      tier: serve
      track: stable
  template:
    metadata:
      labels:
        app: hello
        tier: serve
        track: stable
    spec:
      containers:
        - name: helloserve
          image: fransoaardi/helloserve:v1
          ports:
            - containerPort: 8200
          resources:
            requests:
              cpu: 100m