---
apiVersion: v1
kind: Service
metadata:
  name: http-svc
spec:
  type: ClusterIP
  selector:
    app: hello
    tier: http
    track: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100