---
apiVersion: v1
kind: Service
metadata:
  name: serve-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: serve
    track: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200